import { useEffect, useState } from "react";

/**
 * Loads and caches the official RSS snapshot generated by
 * `npm run fetch:official` (file: `public/data/official-feed-items.json`).
 *
 * Returns: { items, generatedAt, error, loading }
 *
 * The result is module-cached so multiple components mounted simultaneously
 * (sidebar, headlines section, state panel) all share the same network call.
 */
let CACHE = null;
let INFLIGHT = null;

export function useOfficialFeed() {
  const [data, setData] = useState(CACHE);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(!CACHE);

  useEffect(() => {
    if (CACHE) {
      setData(CACHE);
      setLoading(false);
      return;
    }
    let cancelled = false;

    if (!INFLIGHT) {
      INFLIGHT = (async () => {
        try {
          const res = await fetch("/data/official-feed-items.json", { cache: "no-store" });
          if (!res.ok) throw new Error(`HTTP ${res.status}`);
          const json = await res.json();
          CACHE = json;
          return json;
        } finally {
          INFLIGHT = null;
        }
      })();
    }

    INFLIGHT.then(
      (json) => {
        if (cancelled) return;
        setData(json);
        setLoading(false);
      },
      (e) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
        setLoading(false);
      }
    );

    return () => {
      cancelled = true;
    };
  }, []);

  return {
    items: Array.isArray(data?.items) ? data.items : [],
    generatedAt: data?.generatedAt || null,
    sourceReports: Array.isArray(data?.sourceReports) ? data.sourceReports : [],
    error,
    loading,
  };
}
